import './globals.css'
import { Inter, PT_Serif } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const ptser = PT_Serif({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
})

export const metadata = {
  title: 'Enablment - Odelia',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ptser.className}>{children}</body>
    </html>
  )
}
